server:
  port: 8082

spring:
  application:
    name: notification_service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 60000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

notification:
  pin:
    expiration-minutes: 30
    length: 6

security:
  jwt:
    secret: ${JWT_SECRET:PragmaJwtSecret_2026_fK2mQ9xL7vN4pR6tY3wZ1aB5cD8eF0gH}

logging:
  level:
    root: INFO

vonage:
  api-key: ${VONAGE_API_KEY:fcf86937}
  api-secret: ${VONAGE_API_SECRET:zQ)cxL77I(GPy7}

